apiVersion: v1
kind: Service
metadata:
  name: kubelet-serving-cert-approver
  labels:
    app.kubernetes.io/instance: kubelet-serving-cert-approver
    app.kubernetes.io/name: kubelet-serving-cert-approver
spec:
  selector:
    app.kubernetes.io/instance: kubelet-serving-cert-approver
    app.kubernetes.io/name: kubelet-serving-cert-approver
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
