apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver
bases:
- ../base/
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: events:kubelet-serving-cert-approver
  path: rolebindings-patch.yaml
patchesStrategicMerge:
- overlays/deployments.yaml
resources:
- rolebindings.yaml
- roles.yaml
