apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/
namespace: kubelet-serving-cert-approver
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: events:kubelet-serving-cert-approver
  path: rolebindings-patch.yaml
